//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:40 PM IST 
//


package com.usa.his.ed.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.manash.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PlanInfo_QNAME = new QName("", "planInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.manash.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlanInfoType }
     * 
     */
    public PlanInfoType createPlanInfoType() {
        return new PlanInfoType();
    }

    /**
     * Create an instance of {@link PlanDeniedType }
     * 
     */
    public PlanDeniedType createPlanDeniedType() {
        return new PlanDeniedType();
    }

    /**
     * Create an instance of {@link PlanApprovedType }
     * 
     */
    public PlanApprovedType createPlanApprovedType() {
        return new PlanApprovedType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlanInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "planInfo")
    public JAXBElement<PlanInfoType> createPlanInfo(PlanInfoType value) {
        return new JAXBElement<PlanInfoType>(_PlanInfo_QNAME, PlanInfoType.class, null, value);
    }

}
