//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:40 PM IST 
//


package com.usa.his.ed.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for planInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plan-name" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="plan-status" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="case-num" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="planApproved" type="{}planApprovedType"/>
 *         &lt;element name="planDenied" type="{}planDeniedType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planInfoType", propOrder = {
    "planName",
    "planStatus",
    "caseNum",
    "planApproved",
    "planDenied"
})
public class PlanInfoType {

    @XmlElement(name = "plan-name", required = true)
    @XmlSchemaType(name = "date")
    protected String planName;
    @XmlElement(name = "plan-status", required = true)
    @XmlSchemaType(name = "date")
    protected String planStatus;
    @XmlElement(name = "case-num")
    protected int caseNum;
    @XmlElement(required = true)
    protected PlanApprovedType planApproved;
    @XmlElement(required = true)
    protected PlanDeniedType planDenied;

    /**
     * Gets the value of the planName property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * Sets the value of the planName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanName(String value) {
        this.planName = value;
    }

    /**
     * Gets the value of the planStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanStatus() {
        return planStatus;
    }

    /**
     * Sets the value of the planStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanStatus(String value) {
        this.planStatus = value;
    }

    /**
     * Gets the value of the caseNum property.
     * 
     */
    public int getCaseNum() {
        return caseNum;
    }

    /**
     * Sets the value of the caseNum property.
     * 
     */
    public void setCaseNum(int value) {
        this.caseNum = value;
    }

    /**
     * Gets the value of the planApproved property.
     * 
     * @return
     *     possible object is
     *     {@link PlanApprovedType }
     *     
     */
    public PlanApprovedType getPlanApproved() {
        return planApproved;
    }

    /**
     * Sets the value of the planApproved property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanApprovedType }
     *     
     */
    public void setPlanApproved(PlanApprovedType value) {
        this.planApproved = value;
    }

    /**
     * Gets the value of the planDenied property.
     * 
     * @return
     *     possible object is
     *     {@link PlanDeniedType }
     *     
     */
    public PlanDeniedType getPlanDenied() {
        return planDenied;
    }

    /**
     * Sets the value of the planDenied property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanDeniedType }
     *     
     */
    public void setPlanDenied(PlanDeniedType value) {
        this.planDenied = value;
    }

}
