//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:40 PM IST 
//


package com.usa.his.ed.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for planApprovedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planApprovedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plan-start-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="plan-end-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="benefit-amt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planApprovedType", propOrder = {
    "planStartDate",
    "planEndDate",
    "benefitAmt"
})
public class PlanApprovedType {

    @XmlElement(name = "plan-start-date", required = true)
    @XmlSchemaType(name = "date")
    protected String planStartDate;
    @XmlElement(name = "plan-end-date", required = true)
    @XmlSchemaType(name = "date")
    protected String planEndDate;
    @XmlElement(name = "benefit-amt")
    protected double benefitAmt;

    /**
     * Gets the value of the planStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanStartDate() {
        return planStartDate;
    }

    /**
     * Sets the value of the planStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanStartDate(String value) {
        this.planStartDate = value;
    }

    /**
     * Gets the value of the planEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanEndDate() {
        return planEndDate;
    }

    /**
     * Sets the value of the planEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanEndDate(String value) {
        this.planEndDate = value;
    }

    /**
     * Gets the value of the benefitAmt property.
     * 
     */
    public double getBenefitAmt() {
        return benefitAmt;
    }

    /**
     * Sets the value of the benefitAmt property.
     * 
     */
    public void setBenefitAmt(double value) {
        this.benefitAmt = value;
    }

}
