//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:11 PM IST 
//


package com.usa.his.ed.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eligibilitydeterminationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eligibilitydeterminationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CitigenData" type="{}CitigenDataType"/>
 *         &lt;element name="planDetails" type="{}planDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eligibilitydeterminationType", propOrder = {
    "citigenData",
    "planDetails"
})
public class EligibilitydeterminationType {

    @XmlElement(name = "CitigenData", required = true)
    protected CitigenDataType citigenData;
    @XmlElement(required = true)
    protected PlanDetailsType planDetails;

    /**
     * Gets the value of the citigenData property.
     * 
     * @return
     *     possible object is
     *     {@link CitigenDataType }
     *     
     */
    public CitigenDataType getCitigenData() {
        return citigenData;
    }

    /**
     * Sets the value of the citigenData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitigenDataType }
     *     
     */
    public void setCitigenData(CitigenDataType value) {
        this.citigenData = value;
    }

    /**
     * Gets the value of the planDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PlanDetailsType }
     *     
     */
    public PlanDetailsType getPlanDetails() {
        return planDetails;
    }

    /**
     * Sets the value of the planDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanDetailsType }
     *     
     */
    public void setPlanDetails(PlanDetailsType value) {
        this.planDetails = value;
    }

}
