//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:11 PM IST 
//


package com.usa.his.ed.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for medicaidPlanDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="medicaidPlanDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employment-income" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="properties-cost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="other-income" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "medicaidPlanDataType", propOrder = {
    "employmentIncome",
    "propertiesCost",
    "otherIncome"
})
public class MedicaidPlanDataType {

    @XmlElement(name = "employment-income")
    protected double employmentIncome;
    @XmlElement(name = "properties-cost")
    protected double propertiesCost;
    @XmlElement(name = "other-income")
    protected double otherIncome;

    /**
     * Gets the value of the employmentIncome property.
     * 
     */
    public double getEmploymentIncome() {
        return employmentIncome;
    }

    /**
     * Sets the value of the employmentIncome property.
     * 
     */
    public void setEmploymentIncome(double value) {
        this.employmentIncome = value;
    }

    /**
     * Gets the value of the propertiesCost property.
     * 
     */
    public double getPropertiesCost() {
        return propertiesCost;
    }

    /**
     * Sets the value of the propertiesCost property.
     * 
     */
    public void setPropertiesCost(double value) {
        this.propertiesCost = value;
    }

    /**
     * Gets the value of the otherIncome property.
     * 
     */
    public double getOtherIncome() {
        return otherIncome;
    }

    /**
     * Sets the value of the otherIncome property.
     * 
     */
    public void setOtherIncome(double value) {
        this.otherIncome = value;
    }

}
