//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:11 PM IST 
//


package com.usa.his.ed.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.manash.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Eligibilitydetermination_QNAME = new QName("", "eligibilitydetermination");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.manash.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EligibilitydeterminationType }
     * 
     */
    public EligibilitydeterminationType createEligibilitydeterminationType() {
        return new EligibilitydeterminationType();
    }

    /**
     * Create an instance of {@link MedicaidPlanDataType }
     * 
     */
    public MedicaidPlanDataType createMedicaidPlanDataType() {
        return new MedicaidPlanDataType();
    }

    /**
     * Create an instance of {@link SnapPlanDataType }
     * 
     */
    public SnapPlanDataType createSnapPlanDataType() {
        return new SnapPlanDataType();
    }

    /**
     * Create an instance of {@link CitigenDataType }
     * 
     */
    public CitigenDataType createCitigenDataType() {
        return new CitigenDataType();
    }

    /**
     * Create an instance of {@link CcapPlanDataType }
     * 
     */
    public CcapPlanDataType createCcapPlanDataType() {
        return new CcapPlanDataType();
    }

    /**
     * Create an instance of {@link PlanDetailsType }
     * 
     */
    public PlanDetailsType createPlanDetailsType() {
        return new PlanDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EligibilitydeterminationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eligibilitydetermination")
    public JAXBElement<EligibilitydeterminationType> createEligibilitydetermination(EligibilitydeterminationType value) {
        return new JAXBElement<EligibilitydeterminationType>(_Eligibilitydetermination_QNAME, EligibilitydeterminationType.class, null, value);
    }

}
