//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:11 PM IST 
//


package com.usa.his.ed.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for planDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="snapPlanData" type="{}snapPlanDataType"/>
 *         &lt;element name="ccapPlanData" type="{}ccapPlanDataType"/>
 *         &lt;element name="medicaidPlanData" type="{}medicaidPlanDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planDetailsType", propOrder = {
    "snapPlanData",
    "ccapPlanData",
    "medicaidPlanData"
})
public class PlanDetailsType {

    @XmlElement(required = true)
    protected SnapPlanDataType snapPlanData;
    @XmlElement(required = true)
    protected CcapPlanDataType ccapPlanData;
    @XmlElement(required = true)
    protected MedicaidPlanDataType medicaidPlanData;

    /**
     * Gets the value of the snapPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link SnapPlanDataType }
     *     
     */
    public SnapPlanDataType getSnapPlanData() {
        return snapPlanData;
    }

    /**
     * Sets the value of the snapPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnapPlanDataType }
     *     
     */
    public void setSnapPlanData(SnapPlanDataType value) {
        this.snapPlanData = value;
    }

    /**
     * Gets the value of the ccapPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link CcapPlanDataType }
     *     
     */
    public CcapPlanDataType getCcapPlanData() {
        return ccapPlanData;
    }

    /**
     * Sets the value of the ccapPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CcapPlanDataType }
     *     
     */
    public void setCcapPlanData(CcapPlanDataType value) {
        this.ccapPlanData = value;
    }

    /**
     * Gets the value of the medicaidPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link MedicaidPlanDataType }
     *     
     */
    public MedicaidPlanDataType getMedicaidPlanData() {
        return medicaidPlanData;
    }

    /**
     * Sets the value of the medicaidPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicaidPlanDataType }
     *     
     */
    public void setMedicaidPlanData(MedicaidPlanDataType value) {
        this.medicaidPlanData = value;
    }

}
