//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:19:11 PM IST 
//


package com.usa.his.ed.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.usa.his.ed.response.PlanInfoType;


/**
 * <p>Java class for snapPlanDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="snapPlanDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="is-employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "snapPlanDataType", propOrder = {
    "familyIncome",
    "isEmployed",
    "planInfo"
})
public class SnapPlanDataType {

    @XmlElement(name = "family-income")
    protected double familyIncome;
    @XmlElement(name = "is-employed", required = true)
    protected String isEmployed;
    @XmlElement(required = true)
    protected PlanInfoType planInfo;

    /**
     * Gets the value of the familyIncome property.
     * 
     */
    public double getFamilyIncome() {
        return familyIncome;
    }

    /**
     * Sets the value of the familyIncome property.
     * 
     */
    public void setFamilyIncome(double value) {
        this.familyIncome = value;
    }

    /**
     * Gets the value of the isEmployed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEmployed() {
        return isEmployed;
    }

    public PlanInfoType getPlanInfo() {
		return planInfo;
	}

	public void setPlanInfo(PlanInfoType planInfo) {
		this.planInfo = planInfo;
	}

	/**
     * Sets the value of the isEmployed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEmployed(String value) {
        this.isEmployed = value;
    }

}
